# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_started', models.DateTimeField(auto_now_add=True)),
                ('when_ended', models.DateTimeField()),
                ('quiz_hash', models.TextField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts_wrong', models.PositiveIntegerField()),
                ('counts_right', models.PositiveIntegerField()),
                ('lastquizzed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part1', models.TextField(max_length=500)),
                ('part2', models.TextField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='quizitem',
            name='worditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.WordItem'),
        ),
    ]
