# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='when_ended',
            field=models.DateTimeField(blank=True),
        ),
    ]
