# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_quiz_worditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='when_last_used',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 23, 19, 25, 6, 102941, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
