# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_auto_20160125_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='n_words_asked',
            new_name='currentitem',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='worditem',
        ),
        migrations.AddField(
            model_name='quiz',
            name='words_asked',
            field=models.TextField(default=''),
        ),
    ]
