# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_auto_20160125_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_hash',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
