# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_auto_20160125_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='words_correct_first_time',
            field=models.TextField(default=''),
        ),
    ]
