# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_quiz_words_correct_first_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, verbose_name='Leaderboard name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Will be auto-validated once user has clicked on their email link.')),
            ],
        ),
    ]
