# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0012_auto_20160201_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(default='--------------------------------', editable=False, max_length=32)),
                ('was_used', models.BooleanField(default=False)),
                ('time_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddField(
            model_name='token',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocab.Person'),
        ),
    ]
