# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0013_auto_20160201_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='worditem',
            name='person',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='vocab.Person'),
        ),
    ]
