# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0017_auto_20160201_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizworditem',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.Person'),
        ),
    ]
