# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0018_auto_20160201_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizworditem',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quizworditem',
            name='counts_right',
            field=models.IntegerField(),
        ),
    ]
