# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0021_auto_20160202_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizworditem',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='quizworditem',
            name='counts_right',
        ),
        migrations.RemoveField(
            model_name='quizworditem',
            name='counts_wrong',
        ),
        migrations.RemoveField(
            model_name='quizworditem',
            name='lastquizzed',
        ),
        migrations.AddField(
            model_name='worditem',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='worditem',
            name='counts_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worditem',
            name='counts_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worditem',
            name='lastquizzed',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 4, 21, 17, 20, 919310, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
