# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0022_auto_20160204_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizworditem',
            name='person',
        ),
        migrations.RemoveField(
            model_name='quizworditem',
            name='worditem',
        ),
        migrations.DeleteModel(
            name='QuizWordItem',
        ),
    ]
