# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0023_auto_20160204_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='worditem',
            name='answers',
            field=models.TextField(default=''),
        ),
    ]
