# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0024_worditem_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worditem',
            name='answers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
